"""add revoked_tokens table

Revision ID: 20d7c91bb5df
Revises: 534d32e54b2b
Create Date: 2026-06-03 12:49:09.457845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20d7c91bb5df'
down_revision: Union[str, Sequence[str], None] = '534d32e54b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_group_created'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.alter_column('groups', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'pending_claim', 'pending_claim_ready', 'processing', 'succeeded', 'expired', 'failed', 'canceled', 'requires_action', 'disputed', name='paymentstatus', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_payment_settlement_payer'), 'payments', type_='unique')
    op.create_index('uq_active_payment_settlement_payer', 'payments', ['settlement_id', 'payer_id'], unique=True, postgresql_where=sa.text("status NOT IN ('expired', 'failed', 'canceled')"))
    op.drop_index(op.f('ix_recurring_expenses_created_by_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_group_id'), table_name='recurring_expenses')
    op.alter_column('settlement_records', 'method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('in_app', 'interac', 'cash', 'other', 'etransfer', name='settlementmethod', native_enum=False),
               existing_nullable=False)
    op.alter_column('settlement_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'sent', 'settled', 'declined', name='settlementstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settlement_records', 'status',
               existing_type=sa.Enum('pending', 'sent', 'settled', 'declined', name='settlementstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('settlement_records', 'method',
               existing_type=sa.Enum('in_app', 'interac', 'cash', 'other', 'etransfer', name='settlementmethod', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_recurring_expenses_group_id'), 'recurring_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_created_by_id'), 'recurring_expenses', ['created_by_id'], unique=False)
    op.drop_index('uq_active_payment_settlement_payer', table_name='payments', postgresql_where=sa.text("status NOT IN ('expired', 'failed', 'canceled')"))
    op.create_unique_constraint(op.f('uq_payment_settlement_payer'), 'payments', ['settlement_id', 'payer_id'])
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('pending', 'pending_claim', 'pending_claim_ready', 'processing', 'succeeded', 'expired', 'failed', 'canceled', 'requires_action', 'disputed', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('groups', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('response_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_keys_pkey')),
    sa.UniqueConstraint('key', 'user_id', 'endpoint', name=op.f('uq_idempotency_key_user_endpoint'))
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_group_created'), 'audit_logs', ['group_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
