"""add revoked_tokens table

Revision ID: 20d7c91bb5df
Revises: 534d32e54b2b
Create Date: 2026-06-03 12:49:09.457845

This was originally an autogenerated migration captured against a database
whose actual state had drifted from the migration history (likely one of
the hand-patches later found on production). Never adjusted before commit,
it also carried destructive/redundant operations that had nothing to do
with revoked_tokens:

  * DROP TABLE audit_logs / idempotency_keys — both are live tables backing
    AuditLog (app/audit_log.py) and IdempotencyKey (app/idempotency.py),
    never recreated by any later migration. Running this chain from empty
    would silently delete tables the app depends on today.
  * Redundant alter_column() enum conversions on payments.status and
    settlement_records.status/method — already handled by
    20260525_check_constraints_and_status_enums.py earlier in the chain,
    with a stale existing_type (VARCHAR) that no longer matched the actual
    column type by this point.
  * Redundant drop/create of uq_payment_settlement_payer /
    uq_active_payment_settlement_payer — already handled by
    20260524_payment_retry_partial_index.py earlier in the chain.
  * DROP INDEX on ix_recurring_expenses_created_by_id /
    ix_recurring_expenses_group_id with no replacement anywhere downstream.

Stripped down to just this migration's actual new work: the revoked_tokens
table, groups.invite_token becoming nullable, and the
password_reset_tokens.id/user_id TEXT-to-String cleanup.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '20d7c91bb5df'
down_revision: Union[str, Sequence[str], None] = '534d32e54b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.alter_column('groups', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('groups', 'invite_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
