"""add interac_email_logs table

Revision ID: 7af805ecb0e7
Revises: 20d7c91bb5df
Create Date: 2026-06-03 13:33:04.855347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af805ecb0e7'
down_revision: Union[str, Sequence[str], None] = '20d7c91bb5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interac_email_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('raw_subject', sa.String(length=500), nullable=True),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('parsed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parsed_name', sa.String(length=200), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('settlement_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interac_email_logs_matched'), 'interac_email_logs', ['matched'], unique=False)
    op.create_index(op.f('ix_interac_email_logs_received_at'), 'interac_email_logs', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interac_email_logs_received_at'), table_name='interac_email_logs')
    op.drop_index(op.f('ix_interac_email_logs_matched'), table_name='interac_email_logs')
    op.drop_table('interac_email_logs')
    # ### end Alembic commands ###
