"""add auto_confirmed to settlement_records

Revision ID: a107c01bd8f1
Revises: 7af805ecb0e7
Create Date: 2026-06-03 16:32:21.035625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a107c01bd8f1'
down_revision: Union[str, Sequence[str], None] = '7af805ecb0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlement_records', sa.Column('auto_confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlement_records', 'auto_confirmed')
    # ### end Alembic commands ###
